services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: storage
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
